In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [8]:
float_data = pd.Series([1.2,-3.5,np.nan,0])
float_data
float_data.isna()
string_data = pd.Series(['aardvark',np.nan, None, 'avocado'])
string_data.isna()
float_data = pd.Series([1,2,None],dtype='float64')
float_data
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [43]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data = data.dropna()
data[data.notna()]
data = pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3.]])
data
data.dropna()
data.dropna(how='all')
data[4] = np.nan
data.dropna(axis='columns',how='all')
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = np.nan
df.iloc[:2,2]=np.nan
df
df.dropna()
df.dropna(thresh=2)
df.fillna(0)
df.fillna({1:0.5,2:0})
df = pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:,1]=np.nan
df.iloc[4:,2]=np.nan
df
df.ffill()
df.ffill(limit=2)

          0         1         2
0  1.078841 -1.574114 -1.111849
1  0.929740  0.076135 -0.981923
2  0.793012  0.076135  1.462305
3 -0.045949  0.076135  0.397219
4 -1.014202       NaN  0.397219
5  0.534351       NaN  0.397219

In [45]:
data = pd.Series([1.,np.nan,3.5,np.nan,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [51]:
data = pd.DataFrame({'k1':['one','two']*3 + ['two'],'k2':[1,1,2,3,3,4,4]})
data.duplicated()
data.drop_duplicates()
data['v1'] = range(7)
data
data.drop_duplicates(subset=['k1'])
data.drop_duplicates(['k1','k2'],keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6