In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [ ]:
obj = pd.Series([4, 7, -5,3])
obj
obj.array
obj.index
obj.array
obj2 = pd.Series([4, 7, -5,3], index=['d','b','a','c'])
obj2.index
obj2['a']
obj2['d'] = 6
obj2[['c','a','d']]

obj2[obj2 > 0]
obj2 * 2
np.exp(obj2)
'e' in obj2
sdata ={'Ohio':35000, 'Texas':71000, 'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

obj3.to_dict()

states = ['California', 'Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index=states)
obj4

pd.isnull(obj4)
pd.notnull(obj4)
obj3 + obj4
obj4.name = 'population'
obj4.index.name = 'state'
obj4
obj
obj.index =['Bob', 'Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [11]:
data ={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame.head()
frame.tail()
pd.DataFrame(data, columns =['year','state','pop'])
frame2 = pd.DataFrame(data, columns= ['year','state','pop','debt'])
frame2
frame2.columns
frame2['state']
frame2.year
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [12]:
frame2.loc[1]
frame2.iloc[2]
frame2['debt']=16.5
frame2
frame2['debt'] = np.arange(6.)
frame2
val = pd.Series([-1.2, -1.5, -1.7], index=[2,4,5])
frame2['debt'] = val
frame2
frame2['eastern'] = frame2.state =='Ohio'
frame2
del frame2['eastern']
frame2.columns
populations = {'Ohio':{2000:1.5,2001:1.7,2002:3.6},
               'Nevada':{2001:2.4, 2002:2.9}}
frame3 = pd.DataFrame(populations)
frame3
frame3.T
pd.DataFrame(populations, index=[2001,2002,2003])
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)
frame3.index.name = "year"
frame3.columns.name = "state"
frame3
frame3.to_numpy()
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

In [ ]:
obj = pd.Series(range(3), index=['a', 'b','c'])
index = obj.index
index
index[1:]
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index =labels)
obj2
frame3.columns
'Ohio' in frame3.columns
2003 in frame3.index
pd.Index(['foo','foo','bar','bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [25]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index =['d','b','a','c'])
obj
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3
obj3.reindex(range(6), method='ffill')
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=['a','c','d'],
                     columns=['Ohio','Texas','California'])
frame
frame2 = frame.reindex(['a','b','c','d'])
frame2
states = ['Texas','Utah','California']
frame.reindex(columns=states)
frame.reindex(states,axis='columns')
frame.loc[['a','d','c'],['California','Texas']]

   California  Texas
a           2      1
d           8      7
c           5      4