In [1]:
import numpy as np
import pandas as pd
import re
from pandas import Series, DataFrame

In [19]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]
age_categories = pd.cut(ages,bins)
age_categories
age_categories.codes
age_categories.categories
age_categories.categories[0]
age_categories.value_counts()
pd.cut(ages,bins,right=False)
group_names = ['Youth','YoungAdult','MiddleAges','Senior']
pd.cut(ages,bins,labels=group_names)
data = np.random.rand(20)
pd.cut(data,4,precision=2)
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data,4,precision=2)
quartiles
quartiles.value_counts()
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-0.0107, 1.317], (-3.663, -1.252], (-0.0107, 1.317], (-3.663, -1.252], (-0.0107, 1.317], ..., (-0.0107, 1.317], (1.317, 3.158], (-1.252, -0.0107], (-1.252, -0.0107], (-0.0107, 1.317]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.663, -1.252] < (-1.252, -0.0107] < (-0.0107, 1.317] < (1.317, 3.158]]

In [41]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))
data.describe()
col = data[2]
col[np.abs(col)>3]
data[(data.abs() > 3).any(axis='columns')]
data[np.abs(data)>3] = np.sign(data * 3)
data.describe()
np.sign(data).head()
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))
df
sampler = np.random.permutation(5)
sampler
df.take(sampler)
df.iloc[sampler]
column_sampler = np.random.permutation(7)
column_sampler
df.take(column_sampler, axis='columns')
df.sample(n=3)
choices = pd.Series([5,7,-1,6,4])
choices.sample(n=10,replace=True)

2   -1
4    4
3    6
3    6
2   -1
4    4
2   -1
1    7
3    6
4    4
dtype: int64

In [55]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                   'data1': range(6)})
df
pd.get_dummies(df['key'])
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummy =df[['data1']].join(dummies)
df_with_dummy
mnames = ['movie_id','title','genres']
movies = pd.read_table('data/movielens/movies.dat',sep='::', header=None,names=mnames)
movies[:10]

dummies = movies['genres'].str.get_dummies('|')
dummies.iloc[:10,:6]
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]
np.random.seed(12345)
values = np.random.uniform(size=10)
values
bins=[0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

C:\Users\Michał\AppData\Local\Temp\ipykernel_26328\1400433004.py:9: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('data/movielens/movies.dat',sep='::', header=None,names=mnames)

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [13]:
s = pd.Series([1,2,3,None])
s
s.dtype
s = pd.Series([1,2,3,None],dtype = pd.Int64Dtype())
s
s.isna()
s[3] is pd.NA
s = pd.Series([1,2,3,None],dtype='Int64')
s = pd.Series(['one','two',None,'three'], dtype=pd.StringDtype())
s
df = pd.DataFrame({'A':[1,2,None,4],'B':['one','two','three','None'],'C':[False,None,False,True]})
df
df['A'] = df["A"].astype('Int64')
df['B'] = df["B"].astype('string')
df['C'] = df["C"].astype('boolean')
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   None   True

In [ ]:
val = 'a,b, guido'
val.split(',')
pieces = [x.strip() for x in val.split(',')]
pieces
first, second, third = pieces
first + '::'+ second + '::' + third
print('::'.join(pieces))
'guido' in val
val.index(',')
val.find(':')
val.count(',')
val.replace(',','::')
val.replace(',','')

a::b::guido

'ab guido'

In [49]:
text = 'foo bar\tbaz \tqux'
re.split('\s+', text)
regex = re.compile('\s+')
regex.split(text)
regex.findall(text)
text="""Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern =r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)
m=regex.search(text)
m
text[m.start():m.end()]
print(regex.match(text))
print(regex.sub('REDACTED',text))
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)
m = regex.match('wesm@bright.net')
m.groups()
regex.findall(text)
print(regex.sub(r'Username:\1, Domain:\2, Suffix: \3',text))

None
Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED
Dave Username:dave, Domain:google, Suffix: com
Steve Username:steve, Domain:gmail, Suffix: com
Rob Username:rob, Domain:gmail, Suffix: com
Ryan Username:ryan, Domain:yahoo, Suffix: com

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Michał\AppData\Local\Temp\ipykernel_18400\19994105.py:2: SyntaxWarning: invalid escape sequence '\s'
  re.split('\s+', text)
C:\Users\Michał\AppData\Local\Temp\ipykernel_18400\19994105.py:3: SyntaxWarning: invalid escape sequence '\s'
  regex = re.compile('\s+')

In [61]:
data = {'Dave':'dave@google.com', 'Steve':'steve@gmail.com','Rob':'rob@gmail.com','Wes':np.nan}
data = pd.Series(data)
data
data.isna()
data.str.contains('gmail')
data_as_string_ext = data.astype('string')
data_as_string_ext
data_as_string_ext.str.contains('gmail')
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
pattern
data.str.findall(pattern, flags=re.IGNORECASE)
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches
matches.str.get(1)
data.str[:5]
data.str.extract(pattern, flags=re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [7]:
values = pd.Series(['apple','orange','apple','apple'] *2)
values
pd.unique(values)
values.value_counts()
values = pd.Series([0,1,0,0] *2)
dim = pd.Series(['apple','orange'])
values
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: str

In [21]:
fruits = ['apple','orange','apple','apple']*2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df= pd.DataFrame({'fruit':fruits,
              'basket_id':np.arange(N),
              'count':np.random.randint(3,15,size=N),
              'weight':np.random.uniform(0,4,size=N)},
              columns=['basket_id','fruit','count','weight'])
df
fruit_cat = df['fruit'].astype('category')
fruit_cat
c = fruit_cat.array
type(c)
c.categories
c.codes
dict(enumerate(c.categories))
df['fruit'] = df['fruit'].astype('category')
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [25]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])
my_categories
categories = ['foo','bar','baz']
codes = [0,1,2,0,0,1]
my_cats_2 = pd.Categorical.from_codes(codes,categories)
my_cats_2
ordered_cat = pd.Categorical.from_codes(codes,categories,ordered=True)
ordered_cat
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']